<h2><i class="fa fa-lock"></i> Se connecter avec un compte utilisateur</h2>
<?php if (isset($errorMessage)): ?>
	<?= $errorMessage ?>
<?php endif ?>
<form class="generic-form" action="<?= $requestUrl ?>/login" method="POST">

	<aside class="error-message hidden">
		<h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
		
	</aside>

	<fieldset>
		<legend>Informations d'authentification</legend>
		<ul>
			<li>
				<label for="email">E-mail :</label>
				<input id="email" type="text" name="email" >
			</li>
			<li>
				<label for="password">Mot de passe :</label>
				<input id="password" type="password" name="password" >
			</li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input type="submit" value="Connexion">
			<a  href="<?= $requestUrl ?>">Annuler</a>
		</li>
	</ul>
</form>