
<nav class="user-interface">
        <ul class="link-list">
            <li>
            	<a class="btn btn-light" href="<?= $requestUrl ?>/user">Créer un compte</a>
            </li>
            
        </ul>
</nav>


 <!-- Affichage du template lié à la vue -->
        <h2><i class="fa fa-user"></i> Création d'un compte client</h2>

<form class="generic-form" action="<?= $requestUrl ?>/user" method="POST">

	<aside class="error-message hidden">
		<h3><i class="fa fa-warning"></i> Il y a <span id="total-error-count">1</span> erreur(s) dans le formulaire !</h3>
		<p></p>
	</aside>

	<fieldset>
		<legend><i class="fa fa-book"></i> Identité et coordonnées</legend>
		<ul>
			<li>
				<label for="lastname">Nom :</label>
				<input id="lastname" type="text" name="lastname" data-required data-name="Nom" value="">
				<!--input id="lastName" type="text" name="lastName" value=""-->
			</li>
			<li>
				<label for="firstname">Prénom :</label>
				<input id="firstname" type="text" name="firstname" data-required data-name="Prénom" value="">
			</li>
			<li>
				<label for="birthdate">Date de naissance :</label>
				<input type="date" name="birthdate">
			</li>
			<li>
				<label class="textarea" for="address">Adresse :</label>
				<textarea id="address" name="address" rows="3"></textarea>
			</li>
			<li>
				<label for="city">Ville :</label>
				<input id="city" type="text" name="city" value="">
			</li>
			<li>
				<label for="zipcode">Code Postal :</label>
				<input id="zipcode" class="zip-code" type="text" maxlength="5" name="zipcode" data-name="Code postal" data-type="number" value="">
			</li>
			<li>
				<label for="phone">Téléphone :</label>
				<input id="phone" class="phone" type="text" maxlength="10" name="phone" data-name="Téléphone" data-type="number" value="">
			</li>
		</ul>
	</fieldset>

	<fieldset>
		<legend><i class="fa fa-lock"></i> Informations d'authentification</legend>
		<ul>
	        <li>
	            <label for="email">E-mail :</label>
	            <input id="email" type="text" name="email" data-required data-name="E-mail" value="">
	        </li>
	        <li>
	            <label for="password">Mot de passe :</label>
	            <input id="password" type="password" name="password" data-required data-name="Mot de passe" data-length="8">
	        </li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Créer le compte">
			<a class="button button-cancel small" href="/dev/resto/final/index.php">Annuler</a>
		</li>
	</ul>
</form>    
